### ISSUE TITLE
Please think about rename your package to org-<yourchoice>

### ISSUE THREAD

**Issue by triklsbg** [abo-abo/orca#1]
This helps thousands of users to detect the relationship to the Org Universe. Undoubtedly at the first sight of the name via the all kown prefix org-. 
"orca" sounds nice but doesn't show this dependency in the first moment.

Thanks

**Comment by abo-abo** [comment]
I haven't found this to be a problem in the past. The summary and description mentions org-mode and is visible in the package manager.  Additionally, the package header says:

```elisp
;; Keywords: org, convenience
```

It's very easy to filter on MELPA by keyword: https://melpa.org/#/?q=org.
Right now, 239/3769 packages match Org; `orca` is on the second page of the results.

**Comment by ghost** [comment]
I think that might be helpful... there's also a GNOME related project/framework called Orca, which is a screen-reader. That's the first thing that I though of when seeing this package .... 

https://wiki.gnome.org/Projects/Orca

**Comment by abo-abo** [comment]
You have to take namespaces into consideration: Emacs/Orca is sufficiently different from GNOME/Orca.

As another example, I started using Apache/Ivy a few weeks ago: years after I wrote Emacs/Ivy.
